In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import math


In [2]:
iris = load_iris()
X = iris.data
y = iris.target


In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [4]:
class GaussianNaiveBayes:
    def fit(self, X, y):
        """Fit the model to the training data."""
        self.classes = np.unique(y)
        self.mean = {}
        self.var = {}
        self.priors = {}

        for c in self.classes:
            X_c = X[y == c]
            self.mean[c] = X_c.mean(axis=0)
            self.var[c] = X_c.var(axis=0)
            self.priors[c] = X_c.shape[0] / X.shape[0]

    def pdf(self, class_idx, x):
        """Calculate Gaussian Probability Density Function"""
        mean = self.mean[class_idx]
        var = self.var[class_idx]
        numerator = np.exp(-((x - mean) ** 2) / (2 * var))
        denominator = np.sqrt(2 * np.pi * var)
        return numerator / denominator

    def predict_single(self, x):
        """Predict single sample"""
        posteriors = []
        for c in self.classes:
            prior = np.log(self.priors[c])
            class_conditional = np.sum(np.log(self.pdf(c, x)))
            posterior = prior + class_conditional
            posteriors.append(posterior)
        return self.classes[np.argmax(posteriors)]

    def predict(self, X):
        """Predict multiple samples"""
        return np.array([self.predict_single(x) for x in X])


In [6]:
gnb_manual = GaussianNaiveBayes()
gnb_manual.fit(X_train, y_train)
y_pred_manual = gnb_manual.predict(X_test)


In [7]:
print("=== Step-by-Step Implementation ===")
print("Accuracy:", accuracy_score(y_test, y_pred_manual))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_manual))
print("Classification Report:\n", classification_report(y_test, y_pred_manual))



=== Step-by-Step Implementation ===
Accuracy: 0.9777777777777777
Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



In [8]:
from sklearn.naive_bayes import GaussianNB

gnb_sklearn = GaussianNB()
gnb_sklearn.fit(X_train, y_train)
y_pred_sklearn = gnb_sklearn.predict(X_test)

# Evaluation
print("\n=== In-built GaussianNB (sklearn) ===")
print("Accuracy:", accuracy_score(y_test, y_pred_sklearn))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_sklearn))
print("Classification Report:\n", classification_report(y_test, y_pred_sklearn))

# =========================================================
# Compare Both Models
# =========================================================
print("\n✅ Manual vs Sklearn Model Accuracy Comparison:")
print(f"Manual Implementation Accuracy: {accuracy_score(y_test, y_pred_manual):.4f}")
print(f"Sklearn GaussianNB Accuracy:     {accuracy_score(y_test, y_pred_sklearn):.4f}")


=== In-built GaussianNB (sklearn) ===
Accuracy: 0.9777777777777777
Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45


✅ Manual vs Sklearn Model Accuracy Comparison:
Manual Implementation Accuracy: 0.9778
Sklearn GaussianNB Accuracy:     0.9778


In [9]:
from sklearn.naive_bayes import GaussianNB

gnb_sklearn = GaussianNB()
gnb_sklearn.fit(X_train, y_train)
y_pred_sklearn = gnb_sklearn.predict(X_test)

In [10]:
print("\n=== In-built GaussianNB (sklearn) ===")
print("Accuracy:", accuracy_score(y_test, y_pred_sklearn))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_sklearn))
print("Classification Report:\n", classification_report(y_test, y_pred_sklearn))



=== In-built GaussianNB (sklearn) ===
Accuracy: 0.9777777777777777
Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



In [11]:
print("\n✅ Manual vs Sklearn Model Accuracy Comparison:")
print(f"Manual Implementation Accuracy: {accuracy_score(y_test, y_pred_manual):.4f}")
print(f"Sklearn GaussianNB Accuracy:     {accuracy_score(y_test, y_pred_sklearn):.4f}")


✅ Manual vs Sklearn Model Accuracy Comparison:
Manual Implementation Accuracy: 0.9778
Sklearn GaussianNB Accuracy:     0.9778
