In [2]:
import numpy as np 
import pandas as pd 

In [ ]:
#1.a
arr = np.array([1,2,3,6,4,5]) 
np.flip(arr) 


array([5, 4, 6, 3, 2, 1])

In [ ]:
#1.b
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array1.flatten()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [ ]:
#1.c
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
np.array_equal(arr1, arr2)



True

In [17]:
#1.d 
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
def most_frequent_value_and_indices(arr):
    values, counts = np.unique(arr, return_counts=True)
    most_frequent = values[np.argmax(counts)]
    indices = np.where(arr == most_frequent)[0]
    print("Most frequent:", most_frequent)
    print("Indices:", indices) 
most_frequent_value_and_indices(x)
most_frequent_value_and_indices(y)






Most frequent: 1
Indices: [0 5 7 8 9]
Most frequent: 1
Indices: [0 1 2]


In [21]:
#1.e
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(np.sum(gfg) )
print(np.sum(gfg, axis=1)) # row wise sum
print(np.sum(gfg, axis=0)) # column wise sum



45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [22]:
#1.f
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
print("trace",np.trace(n_array)) 
values, vectors = np.linalg.eig(n_array)
print("eigenvalues",values) 
print("eigenvectors", vectors)
print("inverse",np.linalg.inv(n_array))
print("determinant",np.linalg.det(n_array))



trace 176
eigenvalues [98.16835147 28.097044   49.73460452]
eigenvectors [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
inverse [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
determinant 137180.0000000001


In [23]:
#1.g
p1 = [[1, 2], [2, 3]]
q1 = [[4, 5], [6, 7]]
print("dot",np.dot(p1, q1))
print("cov",np.cov(p1, rowvar=False))

p2 = [[1, 2], [2, 3], [4, 5]]
q2 = [[4, 5, 1], [6, 7, 2]]
print("dot", np.dot(p2, q2))
print("cov",np.cov(p2, rowvar=False))




dot [[16 19]
 [26 31]]
cov [[0.5 0.5]
 [0.5 0.5]]
dot [[16 19  5]
 [26 31  8]
 [46 55 14]]
cov [[2.33333333 2.33333333]
 [2.33333333 2.33333333]]


In [26]:
#1.h
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("inner" ,np.inner(x, y))
print("outer")
print(np.outer(x.flatten(), y.flatten()) ) 

inner [[17 52]
 [13 62]]
outer
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [28]:
#2.a
array = np.array([[1, -2, 3], [-4, 5, -6]])
print("absolute", np.abs(array))
print(np.percentile(array, [25, 50, 75]) )      # Flattened
print(np.percentile(array, [25, 50, 75], axis=0))  # Columns
print(np.percentile(array, [25, 50, 75], axis=1)) # Rows
print(np.mean(array))
print(np.median(array))
print(np.std(array)) 


absolute [[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
-0.5
-0.5
3.8622100754188224


In [33]:
#2.b
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("floor",np.floor(a)) 
print("ceil",np.ceil(a))
print("trunc",np.trunc(a))
print("round",np.round(a)) 


floor [-2. -2. -1.  0.  1.  1.  3.]
ceil [-1. -1. -0.  1.  2.  2.  3.]
trunc [-1. -1. -0.  0.  1.  1.  3.]
round [-2. -2. -0.  0.  2.  2.  3.]


In [37]:
#3.a 
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("sort",np.sort(array))
print("argsort",np.argsort(array) )
print("4 smallest sort",np.sort(array)[:4])
print("5 largest sort",np.sort(array)[-5:])


sort [ 10  16  16  52  54  62 453]
argsort [0 3 4 1 5 2 6]
4 smallest sort [10 16 16 52]
5 largest sort [ 16  52  54  62 453]


In [38]:
#3.b
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
array[np.floor(array) == array]

array([1., 2., 3., 2.])

In [39]:
#4.a
import numpy as np
from matplotlib import pyplot as plt
import matplotlib.image as mpimg
import os

def img_to_array(path, save_path='saved_image.txt'):
    img = mpimg.imread(path)
    
    if len(img.shape) == 2:
        print("Grayscale image")
    elif len(img.shape) == 3:
        print("RGB image")
    else:
        print("Unknown format")
    
    # Save the array as a text file
    np.savetxt(save_path, img.reshape(-1, img.shape[-1]) if img.ndim == 3 else img, fmt='%0.3f')
    print(f"Saved to {save_path}")
    return img

In [44]:
img_arr = img_to_array('example.png' )
print(img_arr)




RGB image
Saved to saved_image.txt
[[[0.14901961 0.14901961 0.14901961 1.        ]
  [0.14901961 0.14901961 0.14901961 1.        ]
  [1.         1.         1.         1.        ]
  ...
  [1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]
  [0.14901961 0.14901961 0.14901961 1.        ]]

 [[0.14901961 0.14901961 0.14901961 1.        ]
  [0.14901961 0.14901961 0.14901961 1.        ]
  [1.         1.         1.         1.        ]
  ...
  [1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]
  [0.14901961 0.14901961 0.14901961 1.        ]]

 [[0.14901961 0.14901961 0.14901961 1.        ]
  [0.14901961 0.14901961 0.14901961 1.        ]
  [1.         1.         1.         1.        ]
  ...
  [1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]
  [0.14901961 0.14901961 0.14901961 1.        ]]

 ...

 [[0.14901961 0.14901961 0.14901961 1.        ]
  [0.14901961 0.1490196

In [47]:
#4.b
loaded = np.loadtxt('saved_image.txt')
print(loaded)


[[0.149 0.149 0.149 1.   ]
 [0.149 0.149 0.149 1.   ]
 [1.    1.    1.    1.   ]
 ...
 [0.149 0.149 0.149 1.   ]
 [0.149 0.149 0.149 1.   ]
 [0.149 0.149 0.149 1.   ]]
